routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
})->name('login');

Route::post('/login','Auth\AuthController@login');

Route::group(['middleware' => ['auth']],function (){
    Route::namespace('Dashboard')->group(function (){
        Route::get('dashboard','DashboardController@index')->name('dashboard');
        Route::namespace('Forms')->prefix('forms')->name('forms.')->group(function (){
            Route::get('expense-form','ExpenseFormController@index')->name('expense');
            Route::prefix('advance-form')->name('advance.')->group(function (){
                Route::get('','AdvanceFormController@index')->name('index');
                Route::get('create','AdvanceFormController@createForm')->name('create');
            });
        });
    });
});

app/Models/BudgetLine.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BudgetLine extends Model
{
    protected $guarded = [];
}

app/Models/Country.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    //
}

app/Models/ExpenditureClassification.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ExpenditureClassification extends Model
{
    protected $guarded = [];
}

app/Models/ExpenseForm.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ExpenseForm extends Model
{
    //
}

app/Models/ExpenseFormActivity.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ExpenseFormActivity extends Model
{
    //
}

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $guarded = [];
}

app/Models/Rec.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Rec extends Model
{
    protected $guarded = [];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    protected $appends = ['name'];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getNameAttribute(){
        return $this->first_name .' '. $this->last_name;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index(){
        return view('dashboard.index');
    }
}

app/Http/Controllers/Dashboard/Forms/AdvanceFormController.php
<?php

namespace App\Http\Controllers\Dashboard\Forms;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AdvanceFormController extends Controller
{
    public function index(){
        return view('dashboard.forms.advance-form.index');
    }

    public function createForm(){
        return view('dashboard.forms.advance-form.create');
    }
}

app/Http/Controllers/Dashboard/Forms/ExpenseFormController.php
<?php

namespace App\Http\Controllers\Dashboard\Forms;

use App\Http\Controllers\Controller;
use App\Models\BudgetLine;
use App\Models\Project;
use App\Models\User;
use Illuminate\Http\Request;

class ExpenseFormController extends Controller
{
    public function index(){
        ///
       $project = Project::all();
       $budget = BudgetLine::all();
        $approver = User::all();
        $currency = config('currency');
        return view('dashboard.forms.expense',
        [
            'budget'=>$budget,
            'project'=>$project,
            'approver'=>$approver,
            'currency'=>$currency
        ]);
    }
}

app/Http/Controllers/Dashboard/FormsController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class FormsController extends Controller
{
    //

    function expense()
    {
        # code...
        return view('dashboard.forms.expense');
    }
}

resources/views/dashboard/forms/advance-form/create.blade.php
@extends('layouts.app')
@section('title','Create Advance Form')

@section('content')
    <!-- Begin Page Header-->
    <div class="row">
        <div class="page-header">
            <div class="d-flex align-items-center">
                <h2 class="page-header-title">Create Advance Form</h2>
                {{--<div>
                    <div class="page-header-tools">
                        <a class="btn btn-gradient-01" href="#">Add Form</a>
                    </div>
                </div>--}}
            </div>
        </div>
    </div>
    <!-- End Page Header -->
    <!-- Begin Row -->
    <div class="widget">
        <div class="widget-body">
            <create-advance-form></create-advance-form>
        </div>
    </div>
    <div style="margin-bottom: 20px;"></div>
@endsection

resources/views/dashboard/forms/advance-form/index.blade.php
@extends('layouts.app')
@section('title','Advance Form')

@section('content')
    <!-- Begin Page Header-->
    <div class="row">
        <div class="page-header">
            <div class="d-flex align-items-center">
                <h2 class="page-header-title">Advance Forms</h2>
                <div>
                    <div class="page-header-tools">
                        <a class="btn btn-gradient-01" href="{{route('forms.advance.create')}}">Add Form</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Page Header -->
    <!-- Begin Row -->
    <div class="row flex-row">
        <div class="col-xl-6 col-md-6 os-animation" data-os-animation="fadeInUp">
            <div class="widget widget-21 has-shadow">
                <div class="widget-body h-100 d-flex align-items-center">
                    <div class="section-title">
                        <h3>Acceptance Rate</h3>
                    </div>
                    <div class="hit-rate">
                        <div class="percent"></div>
                    </div>
                    <div class="value-progress text-green">
                        + 34%
                    </div>
                </div>
            </div>
            <div class="widget widget-22 bg-gradient-03">
                <div class="widget-body h-100 d-flex align-items-center">
                    <div class="section-title">
                        <h3>Happy Customers</h3>
                    </div>
                    <div class="happy-customers">
                        <div class="percent"></div>
                    </div>
                    <div class="value-progress">
                        + 54 Today
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-6 col-md-6 os-animation" data-os-animation="fadeInUp">
            <!-- Begin Widget 04 -->
            <div class="widget widget-04 has-shadow">
                <!-- Begin Widget Header -->
                <div class="widget-header bordered d-flex align-items-center">
                    <h2>Post</h2>
                    <div class="widget-options">
                        <div class="dropdown">
                            <button type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                                    class="dropdown-toggle">
                                <i class="la la-ellipsis-h"></i>
                            </button>
                            <div class="dropdown-menu">
                                <a href="#" class="dropdown-item">
                                    <i class="la la-check"></i>Valid Post
                                </a>
                                <a href="#" class="dropdown-item">
                                    <i class="la la-edit"></i>Edit Widget
                                </a>
                                <a href="faq.html" class="dropdown-item faq">
                                    <i class="la la-question-circle"></i>FAQ
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Widget Header -->
                <!-- Begin Widget Body -->
                <div class="widget-body p-0">
                    <div class="post-container">
                        <div class="media mb-3">
                            <div class="media-left align-self-center user">
                                <a href="pages-profile.html"><img src="assets/img/avatar/avatar-07.jpg"
                                                                  class="rounded-circle" alt="..."></a>
                            </div>
                            <div class="media-body align-self-center ml-3">
                                <div class="title">
                                    <span class="username">Lisa Garett</span> posted an image
                                </div>
                                <div class="time">42 min ago</div>
                            </div>
                        </div>
                        <img src="assets/img/background/01.jpg" alt="..." class="img-fluid">
                        <div class="col no-padding d-flex justify-content-end mt-3">
                            <div class="meta">
                                <ul>
                                    <li><a href="#"><i class="la la-comment"></i><span class="numb">38</span></a></li>
                                    <li><a href="#"><i class="la la-heart"></i><span class="numb">94</span></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- Begin Write Comment -->
                    <div class="input-group mt-5">
                        <input type="text" class="form-control pr-0" placeholder="Write a comment ...">
                        <span class="input-group-addon">
                                                <button class="btn" type="button">
                                                    <i class="la la-smile-o la-2x"></i>
                                                </button>
                                            </span>
                        <span class="input-group-addon">
                                                <button class="btn pr-3" type="button">
                                                    <i class="la la-pencil la-2x"></i>
                                                </button>
                                            </span>
                    </div>
                    <!-- End Write Comment -->
                </div>
                <!-- End Widget Body -->
            </div>
            <!-- End Widget 04 -->
        </div>
    </div>
@endsection

resources/views/dashboard/forms/expense.blade.php
@extends('layouts.app')
@section('content')
    <div>
        <form-expense approver="{{json_encode ($approver)}}"></form-expense>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.login')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<!--
Item Name: Elisyam - Web App & Admin Dashboard Template
Version: 1.5
Author: SAEROX

** A license must be purchased in order to legally use this template for your project **
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Solidaridad Forms | @yield('title')</title>
    <meta name="description" content="Elisyam is a Web App and Admin Dashboard Template built with Bootstrap 4">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Google Fonts -->
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
    <script>
        WebFont.load({
            google: {"families":["Montserrat:400,500,600,700","Noto+Sans:400,700"]},
            active: function() {
                sessionStorage.fonts = true;
            }
        });
    </script>
    <!-- Favicon -->
    @include('partials.styles')
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<body id="page-top">
<!-- Begin Preloader -->
@include('partials.loader')
<!-- End Preloader -->
<div id="app" class="page db-modern">
    <!-- Begin Header -->
    <header class="header">
        @include('partials.header')
    </header>
    <!-- End Header -->
    <!-- Begin Page Content -->
    <div class="page-content">
        <!-- Begin Navigation -->
        @include('partials.navigation')
        <!-- End Navigation -->
        <div class="content-inner boxed mt-4 w-100">
            <div class="container">
                @yield('content')

            </div>
            <!-- End Container -->
            <!-- Begin Page Footer-->
            @include('partials.footer')
            <!-- End Page Footer -->
            <a href="#" class="go-top"><i class="la la-arrow-up"></i></a>

        </div>
        <!-- End Content -->
    </div>
    <!-- End Page Content -->
</div>
<!-- Begin Vendor Js -->
<script src="{{asset('js/app.js')}}"></script>
<script src="{{asset('assets/vendors/js/base/core.min.js')}}"></script>
<script src="{{asset('assets/vendors/js/nicescroll/nicescroll.min.js')}}"></script>
<script src="{{asset('assets/vendors/js/waypoints/waypoints.min.js')}}"></script>
<script src="{{asset('assets/vendors/js/chart/chart.min.js')}}"></script>
<script src="{{asset('assets/vendors/js/progress/circle-progress.min.js')}}"></script>

<script src="{{asset('assets/vendors/js/app/app.min.js')}}"></script>
<script src="{{asset('assets/js/dashboard/db-modern.min.js')}}"></script>
<script type="text/javascript">
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>
<!-- End Page Snippets -->
</body>
</html>

resources/views/partials/footer.blade.php
<footer class="main-footer">
    <div class="container">
        <div class="row">
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 d-flex align-items-center justify-content-xl-start justify-content-lg-start justify-content-md-start justify-content-center">
                <p class="text-gradient-02">Design By Saerox</p>
            </div>
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 d-flex align-items-center justify-content-xl-end justify-content-lg-end justify-content-md-end justify-content-center">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="documentation.html">Documentation</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="changelog.html">Changelog</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

resources/views/partials/header.blade.php
<div class="container">
    <nav class="navbar">
        <!-- Begin Search Box-->
        <div class="search-box">
            <button class="dismiss"><i class="ion-close-round"></i></button>
            <form id="searchForm" action="#" role="search">
                <input type="search" placeholder="Search something ..." class="form-control">
            </form>
        </div>
        <!-- End Search Box-->
        <!-- Begin Topbar -->
        <div class="navbar-holder d-flex align-items-center align-middle justify-content-between">
            <!-- Begin Logo -->
            <div class="navbar-header">
                <a href="{{route('dashboard')}}" class="navbar-brand">
                    <div class="brand-image brand-big">
                        <img src="{{asset('logos/Logo diapositive.png')}}" alt="logo" style="height: 40px;margin-left: -15px;" class="logo-big">
                    </div>
                    <div class="brand-image brand-small">
                        <img src="{{asset('logos/Logo diapositive.png')}}" alt="logo" class="logo-small">
                    </div>
                </a>
            </div>
            <!-- End Logo -->
            <!-- Begin Navbar Menu -->
            <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center pull-right">
                <!-- Begin Notifications -->
                <li class="nav-item dropdown"><a id="notifications" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link"><i class="la la-bell animated infinite swing"></i><span class="badge-pulse"></span></a>
                    <ul aria-labelledby="notifications" class="dropdown-menu notification">
                        <li>
                            <div class="notifications-header">
                                <div class="title">Notifications (4)</div>
                                <div class="notifications-overlay"></div>
                                <img src="assets/img/notifications/01.jpg" alt="..." class="img-fluid">
                            </div>
                        </li>
                        <li>
                            <a href="#">
                                <div class="message-icon">
                                    <i class="la la-user"></i>
                                </div>
                                <div class="message-body">
                                    <div class="message-body-heading">
                                        New user registered
                                    </div>
                                    <span class="date">2 hours ago</span>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="message-icon">
                                    <i class="la la-calendar-check-o"></i>
                                </div>
                                <div class="message-body">
                                    <div class="message-body-heading">
                                        New event added
                                    </div>
                                    <span class="date">7 hours ago</span>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="message-icon">
                                    <i class="la la-history"></i>
                                </div>
                                <div class="message-body">
                                    <div class="message-body-heading">
                                        Server rebooted
                                    </div>
                                    <span class="date">7 hours ago</span>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="message-icon">
                                    <i class="la la-twitter"></i>
                                </div>
                                <div class="message-body">
                                    <div class="message-body-heading">
                                        You have 3 new followers
                                    </div>
                                    <span class="date">10 hours ago</span>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a rel="nofollow" href="#" class="dropdown-item all-notifications text-center">View All Notifications</a>
                        </li>
                    </ul>
                </li>
                <!-- End Notifications -->
                <!-- User -->
                <li class="nav-item dropdown"><a id="user" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link">
                        @if(Auth::check() && isset(Auth::user()->avatar))
                            <img src="{{Auth::user()->avatar}}" alt="..." style="object-fit: cover" class="avatar rounded-circle">
                        @else
                            <img src="assets/img/avatar/avatar-01.jpg" alt="..." class="avatar rounded-circle">
                        @endif
                    </a>
                    <ul aria-labelledby="user" class="user-size dropdown-menu">
                        <li class="welcome">
                            <a href="#" class="edit-profil"><i class="la la-gear"></i></a>
                            <img src="assets/img/avatar/avatar-01.jpg" alt="..." class="rounded-circle">
                        </li>
                        <li>
                            <a href="pages-profile.html" class="dropdown-item">
                                Profile
                            </a>
                        </li>
                        <li>
                            <a href="app-mail.html" class="dropdown-item">
                                Messages
                            </a>
                        </li>
                        <li>
                            <a href="#" class="dropdown-item no-padding-bottom">
                                Settings
                            </a>
                        </li>
                        <li class="separator"></li>
                        <li>
                            <a href="pages-faq.html" class="dropdown-item no-padding-top">
                                Faq
                            </a>
                        </li>
                        <li><a rel="nofollow" href="pages-login.html" class="dropdown-item logout text-center"><i class="ti-power-off"></i></a></li>
                    </ul>
                </li>
                <!-- End User -->
            </ul>
            <!-- End Navbar Menu -->
        </div>
        <!-- End Topbar -->
    </nav>
</div>

resources/views/partials/loader.blade.php
<div id="preloader">
    <div class="canvas">
        <img src="{{asset('logos/Logo full colour big.png')}}" alt="logo" class="loader-logo">
        <div class="spinner"></div>
    </div>
</div>

resources/views/partials/navigation.blade.php
<div class="horizontal-menu">
    <div class="container">
        <div class="row">
            <nav class="navbar navbar-light navbar-expand-lg main-menu">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="dropdown">
                            <a class="dropdown-toggle" href="#" id="dashboard" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Forms</a>
                            <ul class="dropdown-menu" aria-labelledby="dashboard">
                                <li><a href="{{route('forms.advance.index')}}">Advance Form</a></li>
                                <li><a href="{{route('forms.expense')}}">Expense Form</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</div>

resources/views/partials/scripts.blade.php
<script src="{{asset('js/app.js')}}"></script>
<script src="{{asset('assets/vendors/js/base/core.min.js')}}"></script>
<script src="{{asset('assets/vendors/js/nicescroll/nicescroll.min.js')}}"></script>
<script src="{{asset('assets/vendors/js/app/app.min.js')}}"></script>

resources/views/partials/styles.blade.php
<link rel="apple-touch-icon" sizes="180x180" href="{{asset('assets/img/apple-touch-icon.png')}}">
<link rel="icon" type="image/png" sizes="32x32" href="{{asset('images/logo/fav-icon-32-32.jpg')}}">
<link rel="icon" type="image/png" sizes="16x16" href="{{asset('images/logo/fav-icon-16-16.jpg')}}">
<!-- Stylesheet -->
<link rel="stylesheet" href="{{asset('css/app.css')}}">
<link rel="stylesheet" href="{{asset('assets/vendors/css/base/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('assets/vendors/css/base/elisyam-1.5.css')}}">